# Generated by Django 2.1.11 on 2020-01-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'User Details', 'verbose_name_plural': 'User Details'},
        ),
    ]
